services:
  app:
    container_name: dish_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:sqlite:/data/dish.db"
      SPRING_PROFILES_ACTIVE: "docker"
      RUNNING_IN_DOCKER: "true"
    volumes:
      - ./Database:/data
