name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Set lower case owner name
      run: |
        echo "OWNER_LC=${OWNER,,}" >> ${GITHUB_ENV}
      env:
        OWNER: '${{ github.repository_owner }}'

    - name: Set image tag
      run: |
        IMAGE_TAG=$(date +%s)
        echo "IMAGE_TAG=${IMAGE_TAG}" >> ${GITHUB_ENV}

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/${{ env.OWNER_LC }}/dish-api:${{ env.IMAGE_TAG }}

    - name: Push the Docker image
      run: docker push ghcr.io/${{ env.OWNER_LC }}/dish-api:${{ env.IMAGE_TAG }}
