name: Build and deploy container app to Azure Web App - dishapi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.AzureAppService_ContainerUsername_9194379b48514f6696aa6faf8c82996e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d6efa59a91f44483b708be1e83be92f2 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/d-i-s-h/dish-api:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dishapi'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_423fcb9cbe83434ea40605e1a552b268 }}
        images: 'ghcr.io/d-i-s-h/dish-api:${{ github.sha }}'
